# Generated by Django 5.1.2 on 2024-10-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='project_previews'),
        ),
    ]
