# Generated by Django 5.1.2 on 2025-08-20 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='summary',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='body',
            field=models.TextField(default=''),
        ),
    ]
